changes/31.feature.md, src/aiotools/server.py
This PR adds a context variable `process_idex` to the `aiotools.server` module so that the worker processes could read the index of current process anywhere.
=> feat: Expose `process_index` context variable for server processes

changes/30.feature.md, src/aiotools/__init__.py, src/aiotools/ptaskgroup.py, tests/test_ptaskgroup.py
=> Implement PersistentTaskGroup

changes/32.feature.md, src/aiotools/taskgroup.py, tests/test_taskgroup.py
Python 3.9 added a `msg` arg to `cancel()`.  If the patched parent task of a task group is cancelled with this argument, we get this error:
```
TypeError: _task_cancel() takes 2 positional arguments but 3 were given
```
This adds a test for this scenario, and then fixes it by adding an optional argument to the wrapper.
=> Support for `msg` arg to `cancel()` added in Python 3.9

changes/35.feature.md, src/aiotools/taskgroup.py, tests/test_taskgroup.py
This attempts to fix #34 .  I'm not quite sure what the intended logic behind the `base_error` stuff was, and as such I'm not sure if I've messed something up here.  But the tests pass!  :)
=> Attempted fix for "unexpected cancel" issue in #34

.github/workflows/default.yml, changes/36.feature.md, docs/aiotools.taskgroup.rst, src/aiotools/__init__.py, src/aiotools/ptaskgroup.py, src/aiotools/taskgroup/__init__.py, src/aiotools/taskgroup/base.py, src/aiotools/taskgroup/base_compat.py, src/aiotools/taskgroup/common.py, src/aiotools/taskgroup/persistent.py, src/aiotools/taskgroup/persistent_compat.py, src/aiotools/taskgroup/types.py, src/aiotools/timer.py, tests/test_ptaskgroup.py, tests/test_taskgroup.py
This PR rewrites `PersistenTaskGroup` for Python 3.11.
~~It works only for the latest Python 3.11 development version checked out from GitHub.~~
It supports `TaskGroup` and `PersistentTaskGroup` on Python 3.6 to 3.11, while `aiotools.TaskGroup` uses the stdlib's implementation on 3.11.0-alpha6 or later.  The test suite ensures the same behavior of the custom implementation and the stdlib.  At the time of writing, Python 3.11.0-alpha5 is the latest available build in GitHub Actions, so the CI runs only the custom implementations but I have checked the same test results on a local build of CPython.
refs https://bugs.python.org/issue46843
=> Rewrite PersistentTaskgroup for Python 3.11

changes/38.feature.md, docs/aiotools.taskgroup.rst, src/aiotools/taskgroup/persistent.py, src/aiotools/taskgroup/persistent_compat.py, tests/test_ptaskgroup.py
=> feat: Implement all_ptaskgroups() and add more tests

changes/41.fix.md, docs/aiotools.taskgroup.rst, src/aiotools/taskgroup/persistent.py, src/aiotools/taskgroup/persistent_compat.py
- fix: Set current_ptaskgroup only in async-with blocks
- docs: Add a warning about the new behavior
=> fix: Set `current_ptaskgroup` only in async-with blocks

changes/42.fix.md, src/aiotools/taskgroup/base_compat.py, src/aiotools/taskgroup/types.py
* Let MultiError inherit ExceptionGroup instead of BaseExceptionGroup,
to be consistent with legacy MultiError.
=> fix: Feature detection for ExceptionGroup

changes/46.fix.md, src/aiotools/fork.py, src/aiotools/server.py
Sometimes interrupting the process using `aiotools.afork()` hangs due to signal race.
Let's minimize the exposed surface of event loops in the child process.
=> server: Add wait_timeout and properly close pipe fds during afork

changes/47.fix.md, src/aiotools/__init__.py
`aiotools.fork` raises error for windows.
The comments on fork module say it supports specific version of linux
```
File "c:\users\user\projects\aiotools\src\aiotools\fork.py", line 41, in <module> 
_libc = ctypes.CDLL(None)  
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__                                                                                               
if '/' in name or '\\' in name: 
```
=> Allow import from windows environment

changes/48.feature.md, src/aiotools/context.py
There are still many cases that implement `close()` as async functions, instead of `aclose()`.
Let's embrace such use cases with `async with closing_async(...)`.
=> Add `closing_async()` async context manager

changes/49.fix.md, src/aiotools/__init__.py, src/aiotools/fork.py
Though `aiotools.fork` and `aiotools.server` modules do not support Windows, importing them is fine.  The previously found error was due to an _unused_ code: `ctypes.CDLL(None)`.
This PR removes those unused codes to avoid confusion and restore the import statements, as #47 has broken imports in macOS.
=> fix: Import in macOS (regression from #47)

changes/51.fix.md, src/aiotools/fork.py, src/aiotools/server.py
* Use os.pidfd_open() that requires a higher kernel version to avoid
a missing API error in Linuxn kernel 5.1 to 5.2.
=> fix: Improve checks for pidfd availability

.github/workflows/default.yml, changes/54.fix.md, src/aiotools/func.py, src/aiotools/server.py, src/aiotools/taskgroup/__init__.py, src/aiotools/taskgroup/persistent.py, src/aiotools/taskgroup/persistent_compat.py, src/aiotools/taskgroup/types.py
- It no longer stores the unhandled exceptions from subtasks,
as they will be kept for the whole lifespan of the
PersistentTaskGroup.
=> Fix a potential memory leak in PersistentTaskGroup

.github/workflows/default.yml, .gitignore, .pre-commit-config.yaml, changes/64.feature.md, setup.cfg, src/aiotools/server.py, src/aiotools/taskgroup/types.py, src/aiotools/types.py
There seems to be no breaking changes yet.
Though, child watchers are going to be deprecated so let's just skip manual configuration of them. (python/cpython#94597)
=> Add Python 3.12 support

.readthedocs.yml, changes/71.feature, setup.cfg, src/aiotools/compat.py, src/aiotools/supervisor.py
`asyncio.tasks._set_task_name()` is now removed as Python 3.13 mandates all 3rd-party event loop implementations to provide `Task.set_name()` method.
Since we have to support prior Python versions, copy the same logic into our `compat` module.
=> Add Python 3.13 compatibility

.github/workflows/timeline-check.yml, changes/72.fix, src/aiotools/taskgroup/__init__.py
After 1.8.0 release, the following code began to generate mypy errors like `Name "aiotools.PersistentTaskGroup" is not defined  [name-defined]`.
This PR updates the declaration of `aiotools.taskgroup.__all__` to be more static-checker friendly, removing no-longer-required branches for pre-3.7 Python versions.
```python
import aiotools
async def something():
async with aiotools.PersistentTaskGroup() as tg:  # <--
...
```
=> Make public exports of `aiotools.taskgroup` static-checker friendly

.github/workflows/timeline-check.yml, README.md
=> doc: Remove deprecated `loop=loop` kwarg in README example

changes/81.fix, src/aiotools/timer.py, tests/test_timer.py
=> fix: Override `loop._clock_resolution` with a coarse-grained value in VirtualClock

.github/workflows/default.yml, changes/84.fix.md, src/aiotools/fork.py, tests/test_fork.py, tests/test_server.py
Attempt to fix init broken on Windows now (hurts our CI/CD). Also (optionally) enable test on Windows. Probably though they were disabled for a reason. Let me know - I can disable it back.
We started hitting the issue after the 1.9.0 release.
```python
E   AttributeError: module 'multiprocessing.context' has no attribute 'ForkProcess'
E   Falsifying example: test_mapper_exception_hypothesis(
E       # The test always failed when commented parts were varied together.
E       create_mapper=datachain.asyn.OrderedMapper,
E       inputs=[(True, 0)],  # or any other generated value
E       workers=1,  # or any other generated value
....
```
```python
C:\a\datachain\datachain\tests\unit\test_asyn.py:192: in test_mapper_hypothesis
with mock_time(loop): …
```
=> Allow importing aiotools in Windows CI
